settings:
  title: '服务今天挂了吗？'
  logo: 'logo.png' # image in ./public/ folder
  daysInHistogram: 180 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '暂时还没挂'
  notAllmonitorsOperational: '挂了一部分'
  monitorLabelOperational: '能用'
  monitorLabelNotOperational: '不能用'
  monitorLabelNoData: '没数据'
  dayInHistogramNoData: '没数据'
  dayInHistogramOperational: '没挂'
  dayInHistogramNotOperational: ' 次无响应' # xx incident(s) recorded

monitors:
  - id: ip-service # unique identifier
    name: IP服务
    description: '返回ipv4地址' # default=empty
    url: 'http://162.14.124.73:52001' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
